# ==============================================================================
# Merged Lakeflow Source: purview
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/purview/purview_schemas.py
    ########################################################

    RETRIABLE_STATUS_CODES = {429, 500, 503}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry
    REQUEST_TIMEOUT = 30  # seconds

    UNIFIED_CATALOG_API_VERSION = "2025-09-15-preview"
    DATA_MAP_API_VERSION = "2023-09-01"

    UNIFIED_CATALOG_BASE_URL = "https://api.purview-service.microsoft.com"
    PURVIEW_TOKEN_SCOPE = "https://purview.azure.net/.default"
    PURVIEW_TOKEN_RESOURCE = "https://purview.azure.net"

    # ---------- systemData struct (shared by domains and data_products) ----------

    SYSTEM_DATA_STRUCT = StructType(
        [
            StructField("createdAt", TimestampType(), nullable=True),
            StructField("createdBy", StringType(), nullable=True),
            StructField("lastModifiedAt", TimestampType(), nullable=True),
            StructField("lastModifiedBy", StringType(), nullable=True),
            StructField("expiredAt", TimestampType(), nullable=True),
            StructField("expiredBy", StringType(), nullable=True),
        ]
    )

    # ---------- domains schema ----------

    PARENT_COLLECTION_STRUCT = StructType(
        [
            StructField("refName", StringType(), nullable=True),
            StructField("type", StringType(), nullable=True),
        ]
    )

    RELATED_COLLECTION_STRUCT = StructType(
        [
            StructField("name", StringType(), nullable=True),
            StructField("friendlyName", StringType(), nullable=True),
            StructField("parentCollection", PARENT_COLLECTION_STRUCT, nullable=True),
        ]
    )

    PLATFORM_DOMAIN_STRUCT = StructType(
        [
            StructField("name", StringType(), nullable=True),
            StructField("friendlyName", StringType(), nullable=True),
            StructField(
                "relatedCollections",
                ArrayType(RELATED_COLLECTION_STRUCT),
                nullable=True,
            ),
        ]
    )

    MANAGED_ATTRIBUTE_STRUCT = StructType(
        [
            StructField("name", StringType(), nullable=True),
            StructField("value", StringType(), nullable=True),
            StructField("isRequired", BooleanType(), nullable=True),
        ]
    )

    DOMAINS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("name", StringType(), nullable=False),
            StructField("description", StringType(), nullable=True),
            StructField("parentId", StringType(), nullable=True),
            StructField("status", StringType(), nullable=False),
            StructField("type", StringType(), nullable=False),
            StructField("isRestricted", BooleanType(), nullable=True),
            StructField(
                "thumbnail",
                StructType([StructField("color", StringType(), nullable=True)]),
                nullable=True,
            ),
            StructField("domains", ArrayType(PLATFORM_DOMAIN_STRUCT), nullable=True),
            StructField(
                "managedAttributes",
                ArrayType(MANAGED_ATTRIBUTE_STRUCT),
                nullable=True,
            ),
            StructField("systemData", SYSTEM_DATA_STRUCT, nullable=True),
        ]
    )

    DOMAINS_METADATA = {
        "primary_keys": ["id"],
        "cursor_field": "",
        "ingestion_type": "snapshot",
    }

    # ---------- data_products schema ----------

    CONTACT_ENTRY_STRUCT = StructType(
        [
            StructField("id", StringType(), nullable=True),
            StructField("description", StringType(), nullable=True),
        ]
    )

    CONTACTS_STRUCT = StructType(
        [
            StructField("owner", ArrayType(CONTACT_ENTRY_STRUCT), nullable=True),
            StructField("expert", ArrayType(CONTACT_ENTRY_STRUCT), nullable=True),
            StructField("databaseAdmin", ArrayType(CONTACT_ENTRY_STRUCT), nullable=True),
        ]
    )

    LINK_STRUCT = StructType(
        [
            StructField("url", StringType(), nullable=True),
            StructField("name", StringType(), nullable=True),
            StructField("dataAssetId", StringType(), nullable=True),
        ]
    )

    ADDITIONAL_PROPERTIES_STRUCT = StructType(
        [
            StructField("assetCount", LongType(), nullable=True),
        ]
    )

    DATA_PRODUCTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("name", StringType(), nullable=False),
            StructField("domain", StringType(), nullable=False),
            StructField("type", StringType(), nullable=False),
            StructField("description", StringType(), nullable=True),
            StructField("businessUse", StringType(), nullable=True),
            StructField("status", StringType(), nullable=False),
            StructField("endorsed", BooleanType(), nullable=False),
            StructField("updateFrequency", StringType(), nullable=True),
            StructField("sensitivityLabel", StringType(), nullable=True),
            StructField("dataQualityScore", DoubleType(), nullable=True),
            StructField("activeSubscriberCount", LongType(), nullable=True),
            StructField("audience", ArrayType(StringType()), nullable=True),
            StructField("contacts", CONTACTS_STRUCT, nullable=True),
            StructField("termsOfUse", ArrayType(LINK_STRUCT), nullable=True),
            StructField("documentation", ArrayType(LINK_STRUCT), nullable=True),
            StructField(
                "managedAttributes",
                ArrayType(MANAGED_ATTRIBUTE_STRUCT),
                nullable=True,
            ),
            StructField("additionalProperties", ADDITIONAL_PROPERTIES_STRUCT, nullable=True),
            StructField("systemData", SYSTEM_DATA_STRUCT, nullable=True),
        ]
    )

    DATA_PRODUCTS_METADATA = {
        "primary_keys": ["id"],
        "cursor_field": "",
        "ingestion_type": "snapshot",
    }

    # ---------- data_assets schema (from search query results) ----------

    TERM_STRUCT = StructType(
        [
            StructField("name", StringType(), nullable=True),
            StructField("glossaryName", StringType(), nullable=True),
            StructField("guid", StringType(), nullable=True),
        ]
    )

    ASSET_CONTACT_STRUCT = StructType(
        [
            StructField("id", StringType(), nullable=True),
            StructField("info", StringType(), nullable=True),
            StructField("contactType", StringType(), nullable=True),
        ]
    )

    DATA_ASSETS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("qualifiedName", StringType(), nullable=False),
            StructField("name", StringType(), nullable=False),
            StructField("description", StringType(), nullable=True),
            StructField("owner", StringType(), nullable=True),
            StructField("entityType", StringType(), nullable=False),
            StructField("assetType", ArrayType(StringType()), nullable=True),
            StructField("classification", ArrayType(StringType()), nullable=True),
            StructField("label", ArrayType(StringType()), nullable=True),
            StructField("term", ArrayType(TERM_STRUCT), nullable=True),
            StructField("contact", ArrayType(ASSET_CONTACT_STRUCT), nullable=True),
            StructField("createTime", LongType(), nullable=True),
            StructField("updateTime", LongType(), nullable=True),
            StructField("endorsement", StringType(), nullable=True),
        ]
    )

    DATA_ASSETS_METADATA = {
        "primary_keys": ["id"],
        "cursor_field": "updateTime",
        "ingestion_type": "cdc",
    }

    # ---------- table registry ----------

    TABLE_SCHEMAS = {
        "domains": DOMAINS_SCHEMA,
        "data_products": DATA_PRODUCTS_SCHEMA,
        "data_assets": DATA_ASSETS_SCHEMA,
    }

    TABLE_METADATA = {
        "domains": DOMAINS_METADATA,
        "data_products": DATA_PRODUCTS_METADATA,
        "data_assets": DATA_ASSETS_METADATA,
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/purview/purview.py
    ########################################################

    _TABLES = ["domains", "data_products", "data_assets"]

    # Default lookback for data_assets incremental reads: 1 hour in ms.
    _LOOKBACK_MS = 3_600_000


    class PurviewLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect + SupportsPartitionedStream implementation for Microsoft Purview."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._account_name = options["purview_account_name"]
            self._auth_method = options.get("auth_method", "default_credential")

            # Resolved lazily and cached.
            self._access_token: str | None = None
            self._token_expires_at: float = 0.0

            # Cap cursors at init time so a trigger never chases new data.
            self._init_ts_ms = int(datetime.now(timezone.utc).timestamp() * 1000)

            # Track whether lookback has been applied in the current trigger for data_assets.
            self._lookback_applied = False

        # ------------------------------------------------------------------
        # Auth helpers
        # ------------------------------------------------------------------

        def _get_access_token(self) -> str:
            """Return a valid bearer token, refreshing if expired."""
            now = time.time()
            if self._access_token and now < self._token_expires_at - 60:
                return self._access_token

            if self._auth_method == "client_secret":
                self._access_token = self._get_token_client_secret()
            else:
                self._access_token = self._get_token_default_credential()

            return self._access_token

        def _get_token_default_credential(self) -> str:
            from azure.identity import DefaultAzureCredential

            credential = DefaultAzureCredential()
            token = credential.get_token(PURVIEW_TOKEN_SCOPE)
            self._token_expires_at = token.expires_on
            return token.token

        def _get_token_client_secret(self) -> str:
            tenant_id = self.options["tenant_id"]
            client_id = self.options["client_id"]
            client_secret = self.options["client_secret"]

            token_url = f"https://login.microsoftonline.com/{tenant_id}/oauth2/token"
            payload = {
                "client_id": client_id,
                "client_secret": client_secret,
                "grant_type": "client_credentials",
                "resource": PURVIEW_TOKEN_RESOURCE,
            }
            resp = requests.post(token_url, data=payload, timeout=REQUEST_TIMEOUT)
            resp.raise_for_status()
            body = resp.json()
            self._token_expires_at = time.time() + int(body.get("expires_in", 3600))
            return body["access_token"]

        def _headers(self) -> dict[str, str]:
            return {
                "Authorization": f"Bearer {self._get_access_token()}",
                "Content-Type": "application/json",
            }

        # ------------------------------------------------------------------
        # Base URLs
        # ------------------------------------------------------------------

        @property
        def _unified_catalog_url(self) -> str:
            return UNIFIED_CATALOG_BASE_URL

        @property
        def _data_map_url(self) -> str:
            return f"https://{self._account_name}.purview.azure.com"

        # ------------------------------------------------------------------
        # HTTP helper with retry
        # ------------------------------------------------------------------

        def _request_with_retry(self, method: str, url: str, **kwargs) -> requests.Response:
            """Issue an HTTP request with exponential backoff on retriable errors."""
            kwargs.setdefault("timeout", REQUEST_TIMEOUT)
            backoff = INITIAL_BACKOFF
            resp = None
            for attempt in range(MAX_RETRIES):
                headers = self._headers()
                if method == "GET":
                    resp = requests.get(url, headers=headers, **kwargs)
                elif method == "POST":
                    resp = requests.post(url, headers=headers, **kwargs)
                else:
                    raise ValueError(f"Unsupported HTTP method: {method}")

                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp

                # Respect Retry-After header if present.
                retry_after = resp.headers.get("Retry-After")
                wait = float(retry_after) if retry_after else backoff

                if attempt < MAX_RETRIES - 1:
                    time.sleep(wait)
                    backoff *= 2

            return resp  # type: ignore[return-value]

        # ------------------------------------------------------------------
        # LakeflowConnect interface
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read records. Used by simpleStreamReader for snapshot tables
            and as fallback for data_assets."""
            self._validate_table(table_name)

            if table_name == "domains":
                return self._read_domains()
            elif table_name == "data_products":
                return self._read_data_products()
            elif table_name == "data_assets":
                return self._read_data_assets_incremental(start_offset, table_options)
            else:
                raise ValueError(f"Unknown table: {table_name}")

        # ------------------------------------------------------------------
        # SupportsPartitionedStream interface
        # ------------------------------------------------------------------

        def is_partitioned(self, table_name: str) -> bool:
            """Only data_assets uses partitioned streaming."""
            return table_name == "data_assets"

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the current high-water mark for data_assets.

            This is a lightweight call -- we use the current wall-clock time
            (capped at init time) as the latest offset rather than querying
            the API, since data_assets uses modifiedTime range queries.
            """
            if table_name != "data_assets":
                raise ValueError(f"latest_offset not supported for non-partitioned table: {table_name}")

            # The latest available offset is the init timestamp.
            return {"cursor_ms": self._init_ts_ms}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Split data_assets time range into partitions for parallel reads."""
            if table_name != "data_assets":
                raise ValueError(
                    f"get_partitions not supported for non-partitioned table: {table_name}"
                )

            # Batch mode: partition the entire table as a single partition.
            if start_offset is None and end_offset is None:
                return [{"since_ms": 0, "until_ms": self._init_ts_ms}]

            if start_offset == end_offset:
                return []

            start_ms = (start_offset or {}).get("cursor_ms", 0)
            end_ms = (end_offset or {}).get("cursor_ms", self._init_ts_ms)

            if start_ms >= end_ms:
                return []

            # Split the range into windows. The window size is configurable
            # via table_options["window_seconds"] (default: 86400 = 1 day).
            window_ms = int(table_options.get("window_seconds", "86400")) * 1000

            partitions = []
            current = start_ms
            while current < end_ms:
                partition_end = min(current + window_ms, end_ms)
                partitions.append({"since_ms": current, "until_ms": partition_end})
                current = partition_end

            return partitions

        def read_partition(
            self,
            table_name: str,
            partition: dict,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Read data_assets for a single time-range partition.

            Runs on executors -- re-creates auth and fetches data independently.
            """
            if table_name != "data_assets":
                raise ValueError(
                    f"read_partition not supported for non-partitioned table: {table_name}"
                )

            since_ms = partition["since_ms"]
            until_ms = partition["until_ms"]
            limit = int(table_options.get("page_size", "1000"))
            max_records = int(table_options.get("max_records_per_batch", "10000"))

            # Apply lookback on the since side.
            query_since_ms = max(0, since_ms - _LOOKBACK_MS) if since_ms > 0 else 0

            url = f"{self._data_map_url}/datamap/api/search/query"
            params = {"api-version": DATA_MAP_API_VERSION}

            filter_clauses = []
            if query_since_ms > 0:
                filter_clauses.append(
                    {
                        "attributeName": "modifiedTime",
                        "operator": "ge",
                        "attributeValue": query_since_ms,
                    }
                )
            if until_ms < self._init_ts_ms:
                filter_clauses.append(
                    {
                        "attributeName": "modifiedTime",
                        "operator": "le",
                        "attributeValue": until_ms,
                    }
                )

            search_filter: dict | None = None
            if len(filter_clauses) == 1:
                search_filter = filter_clauses[0]
            elif len(filter_clauses) > 1:
                search_filter = {"and": filter_clauses}

            body: dict = {
                "keywords": None,
                "limit": limit,
                "continuationToken": None,
            }
            if search_filter:
                body["filter"] = search_filter

            records: list[dict] = []
            while True:
                resp = self._request_with_retry("POST", url, params=params, json=body)
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to query data_assets: {resp.status_code} {resp.text}")
                data = resp.json()
                batch = data.get("value", [])
                for item in batch:
                    records.append(self._normalize_asset(item))

                if len(records) >= max_records:
                    break

                token = data.get("continuationToken")
                if not token:
                    break
                body["continuationToken"] = token

            return iter(records)

        # ------------------------------------------------------------------
        # Snapshot readers (domains, data_products)
        # ------------------------------------------------------------------

        def _read_domains(self) -> tuple[Iterator[dict], dict]:
            """Full snapshot read of all business domains."""
            url = f"{self._unified_catalog_url}/datagovernance/catalog/businessdomains"
            params: dict[str, str] = {"api-version": UNIFIED_CATALOG_API_VERSION}

            records: list[dict] = []
            while url:
                resp = self._request_with_retry("GET", url, params=params)
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to read domains: {resp.status_code} {resp.text}")
                data = resp.json()
                records.extend(data.get("value", []))
                url = data.get("nextLink")
                params = {}  # nextLink already contains query params

            return iter(records), {}

        def _read_data_products(self) -> tuple[Iterator[dict], dict]:
            """Full snapshot read of all data products."""
            url = f"{self._unified_catalog_url}/datagovernance/catalog/dataProducts"
            params: dict[str, str] = {
                "api-version": UNIFIED_CATALOG_API_VERSION,
                "skip": "0",
                "top": "100",
            }

            records: list[dict] = []
            while url:
                resp = self._request_with_retry("GET", url, params=params)
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to read data_products: {resp.status_code} {resp.text}")
                data = resp.json()
                records.extend(data.get("value", []))
                url = data.get("nextLink")
                params = {}  # nextLink already contains query params

            return iter(records), {}

        # ------------------------------------------------------------------
        # Incremental reader for data_assets (used by simpleStreamReader fallback)
        # ------------------------------------------------------------------

        def _read_data_assets_incremental(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Sliding time-window incremental read for data_assets.

            Used when the table falls back to simpleStreamReader (non-partitioned path).
            """
            since_ms = start_offset.get("cursor_ms") if start_offset else None
            if since_ms is None:
                # Try user-supplied start_timestamp (Unix ms).
                start_ts = table_options.get("start_timestamp")
                if start_ts:
                    since_ms = int(start_ts)
                else:
                    since_ms = 0

            # Short-circuit if already caught up.
            if since_ms >= self._init_ts_ms:
                return iter([]), start_offset or {}

            window_ms = int(table_options.get("window_seconds", "86400")) * 1000
            max_records = int(table_options.get("max_records_per_batch", "1000"))
            limit = int(table_options.get("page_size", "1000"))

            until_ms = min(since_ms + window_ms, self._init_ts_ms)

            # Apply lookback only on the first call of the trigger.
            query_since_ms = since_ms
            if not self._lookback_applied and since_ms > 0:
                query_since_ms = max(0, since_ms - _LOOKBACK_MS)
                self._lookback_applied = True

            url = f"{self._data_map_url}/datamap/api/search/query"
            params = {"api-version": DATA_MAP_API_VERSION}

            filter_clauses = []
            if query_since_ms > 0:
                filter_clauses.append(
                    {
                        "attributeName": "modifiedTime",
                        "operator": "ge",
                        "attributeValue": query_since_ms,
                    }
                )
            filter_clauses.append(
                {
                    "attributeName": "modifiedTime",
                    "operator": "le",
                    "attributeValue": until_ms,
                }
            )

            search_filter: dict
            if len(filter_clauses) == 1:
                search_filter = filter_clauses[0]
            else:
                search_filter = {"and": filter_clauses}

            body: dict = {
                "keywords": None,
                "limit": limit,
                "continuationToken": None,
                "filter": search_filter,
            }

            records: list[dict] = []
            while True:
                resp = self._request_with_retry("POST", url, params=params, json=body)
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to query data_assets: {resp.status_code} {resp.text}")
                data = resp.json()
                batch = data.get("value", [])
                for item in batch:
                    records.append(self._normalize_asset(item))

                if len(records) >= max_records:
                    break

                token = data.get("continuationToken")
                if not token:
                    break
                body["continuationToken"] = token

            # Advance cursor to window end regardless of whether records were found,
            # so the next call slides forward.
            end_offset = {"cursor_ms": until_ms}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        # ------------------------------------------------------------------
        # Helpers
        # ------------------------------------------------------------------

        @staticmethod
        def _normalize_asset(item: dict) -> dict:
            """Normalize a search query result into a flat record matching DATA_ASSETS_SCHEMA."""
            return {
                "id": item.get("id"),
                "qualifiedName": item.get("qualifiedName"),
                "name": item.get("name"),
                "description": item.get("description"),
                "owner": item.get("owner"),
                "entityType": item.get("entityType"),
                "assetType": item.get("assetType"),
                "classification": item.get("classification"),
                "label": item.get("label"),
                "term": item.get("term"),
                "contact": item.get("contact"),
                "createTime": item.get("createTime"),
                "updateTime": item.get("updateTime"),
                "endorsement": item.get("endorsement"),
            }

        def _validate_table(self, table_name: str) -> None:
            if table_name not in _TABLES:
                raise ValueError(f"Table '{table_name}' is not supported. Supported tables: {_TABLES}")


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = PurviewLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
